window.esdocSearchIndex = [
  [
    "@hiherto-elements/natural/src/tokenizers/aggressive-tokenizer.js~aggressivetokenizer",
    "class/src/tokenizers/aggressive-tokenizer.js~AggressiveTokenizer.html",
    "<span>AggressiveTokenizer</span> <span class=\"search-result-import-path\">@hiherto-elements/natural/src/tokenizers/aggressive-tokenizer.js</span>",
    "class"
  ],
  [
    "@hiherto-elements/natural/src/util/bag.js~bag",
    "class/src/util/bag.js~Bag.html",
    "<span>Bag</span> <span class=\"search-result-import-path\">@hiherto-elements/natural/src/util/bag.js</span>",
    "class"
  ],
  [
    "@hiherto-elements/natural/src/tokenizers/case-tokenizer.js~casetokenizer",
    "class/src/tokenizers/case-tokenizer.js~CaseTokenizer.html",
    "<span>CaseTokenizer</span> <span class=\"search-result-import-path\">@hiherto-elements/natural/src/tokenizers/case-tokenizer.js</span>",
    "class"
  ],
  [
    "@hiherto-elements/natural/src/classifiers/classifier.js~classifier",
    "function/index.html#static-function-Classifier",
    "<span>Classifier</span> <span class=\"search-result-import-path\">@hiherto-elements/natural/src/classifiers/classifier.js</span>",
    "function"
  ],
  [
    "@hiherto-elements/natural/src/tokenizers/regexp-tokenizer.js~regexptokenizer",
    "class/src/tokenizers/regexp-tokenizer.js~RegexpTokenizer.html",
    "<span>RegexpTokenizer</span> <span class=\"search-result-import-path\">@hiherto-elements/natural/src/tokenizers/regexp-tokenizer.js</span>",
    "class"
  ],
  [
    "@hiherto-elements/natural/src/tokenizers/sentence-tokenizer.js~sentencetokenizer",
    "class/src/tokenizers/sentence-tokenizer.js~SentenceTokenizer.html",
    "<span>SentenceTokenizer</span> <span class=\"search-result-import-path\">@hiherto-elements/natural/src/tokenizers/sentence-tokenizer.js</span>",
    "class"
  ],
  [
    "@hiherto-elements/natural/src/tokenizers/tokenizer.js~tokenizer",
    "class/src/tokenizers/tokenizer.js~Tokenizer.html",
    "<span>Tokenizer</span> <span class=\"search-result-import-path\">@hiherto-elements/natural/src/tokenizers/tokenizer.js</span>",
    "class"
  ],
  [
    "@hiherto-elements/natural/src/util/topological.js~topological",
    "class/src/util/topological.js~Topological.html",
    "<span>Topological</span> <span class=\"search-result-import-path\">@hiherto-elements/natural/src/util/topological.js</span>",
    "class"
  ],
  [
    "@hiherto-elements/natural/src/tokenizers/treebank-word-tokenizer.js~treebankwordtokenizer",
    "class/src/tokenizers/treebank-word-tokenizer.js~TreebankWordTokenizer.html",
    "<span>TreebankWordTokenizer</span> <span class=\"search-result-import-path\">@hiherto-elements/natural/src/tokenizers/treebank-word-tokenizer.js</span>",
    "class"
  ],
  [
    "@hiherto-elements/natural/src/util/utils.js~flip",
    "function/index.html#static-function-flip",
    "<span>flip</span> <span class=\"search-result-import-path\">@hiherto-elements/natural/src/util/utils.js</span>",
    "function"
  ],
  [
    "@hiherto-elements/natural/src/util/utils.js~merge",
    "function/index.html#static-function-merge",
    "<span>merge</span> <span class=\"search-result-import-path\">@hiherto-elements/natural/src/util/utils.js</span>",
    "function"
  ],
  [
    "@hiherto-elements/natural/src/tokenizers/orthography_matchers.js~orthographymatchers",
    "variable/index.html#static-variable-orthographyMatchers",
    "<span>orthographyMatchers</span> <span class=\"search-result-import-path\">@hiherto-elements/natural/src/tokenizers/orthography_matchers.js</span>",
    "variable"
  ],
  [
    "@hiherto-elements/natural/src/util/utils.js~replacer",
    "function/index.html#static-function-replacer",
    "<span>replacer</span> <span class=\"search-result-import-path\">@hiherto-elements/natural/src/util/utils.js</span>",
    "function"
  ],
  [
    "@hiherto-elements/natural/src/stemmers/stemmer.js~stemmer",
    "function/index.html#static-function-stemmer",
    "<span>stemmer</span> <span class=\"search-result-import-path\">@hiherto-elements/natural/src/stemmers/stemmer.js</span>",
    "function"
  ],
  [
    "@hiherto-elements/natural/src/util/stopwords.js~stopwords",
    "variable/index.html#static-variable-stopwords",
    "<span>stopwords</span> <span class=\"search-result-import-path\">@hiherto-elements/natural/src/util/stopwords.js</span>",
    "variable"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/classifiers/classifier.js",
    "file/src/classifiers/classifier.js.html",
    "src/classifiers/classifier.js",
    "file"
  ],
  [
    "src/stemmers/stemmer.js",
    "file/src/stemmers/stemmer.js.html",
    "src/stemmers/stemmer.js",
    "file"
  ],
  [
    "src/tokenizers/aggressive-tokenizer.js",
    "file/src/tokenizers/aggressive-tokenizer.js.html",
    "src/tokenizers/aggressive-tokenizer.js",
    "file"
  ],
  [
    "src/tokenizers/aggressive-tokenizer.js~aggressivetokenizer#constructor",
    "class/src/tokenizers/aggressive-tokenizer.js~AggressiveTokenizer.html#instance-constructor-constructor",
    "src/tokenizers/aggressive-tokenizer.js~AggressiveTokenizer#constructor",
    "method"
  ],
  [
    "src/tokenizers/aggressive-tokenizer.js~aggressivetokenizer#tokenize",
    "class/src/tokenizers/aggressive-tokenizer.js~AggressiveTokenizer.html#instance-method-tokenize",
    "src/tokenizers/aggressive-tokenizer.js~AggressiveTokenizer#tokenize",
    "method"
  ],
  [
    "src/tokenizers/case-tokenizer.js",
    "file/src/tokenizers/case-tokenizer.js.html",
    "src/tokenizers/case-tokenizer.js",
    "file"
  ],
  [
    "src/tokenizers/case-tokenizer.js~casetokenizer#attach",
    "class/src/tokenizers/case-tokenizer.js~CaseTokenizer.html#instance-method-attach",
    "src/tokenizers/case-tokenizer.js~CaseTokenizer#attach",
    "method"
  ],
  [
    "src/tokenizers/case-tokenizer.js~casetokenizer#constructor",
    "class/src/tokenizers/case-tokenizer.js~CaseTokenizer.html#instance-constructor-constructor",
    "src/tokenizers/case-tokenizer.js~CaseTokenizer#constructor",
    "method"
  ],
  [
    "src/tokenizers/case-tokenizer.js~casetokenizer#tokenize",
    "class/src/tokenizers/case-tokenizer.js~CaseTokenizer.html#instance-method-tokenize",
    "src/tokenizers/case-tokenizer.js~CaseTokenizer#tokenize",
    "method"
  ],
  [
    "src/tokenizers/orthography_matchers.js",
    "file/src/tokenizers/orthography_matchers.js.html",
    "src/tokenizers/orthography_matchers.js",
    "file"
  ],
  [
    "src/tokenizers/regexp-tokenizer.js",
    "file/src/tokenizers/regexp-tokenizer.js.html",
    "src/tokenizers/regexp-tokenizer.js",
    "file"
  ],
  [
    "src/tokenizers/regexp-tokenizer.js~regexptokenizer#_gaps",
    "class/src/tokenizers/regexp-tokenizer.js~RegexpTokenizer.html#instance-member-_gaps",
    "src/tokenizers/regexp-tokenizer.js~RegexpTokenizer#_gaps",
    "member"
  ],
  [
    "src/tokenizers/regexp-tokenizer.js~regexptokenizer#_pattern",
    "class/src/tokenizers/regexp-tokenizer.js~RegexpTokenizer.html#instance-member-_pattern",
    "src/tokenizers/regexp-tokenizer.js~RegexpTokenizer#_pattern",
    "member"
  ],
  [
    "src/tokenizers/regexp-tokenizer.js~regexptokenizer#constructor",
    "class/src/tokenizers/regexp-tokenizer.js~RegexpTokenizer.html#instance-constructor-constructor",
    "src/tokenizers/regexp-tokenizer.js~RegexpTokenizer#constructor",
    "method"
  ],
  [
    "src/tokenizers/regexp-tokenizer.js~regexptokenizer#discardempty",
    "class/src/tokenizers/regexp-tokenizer.js~RegexpTokenizer.html#instance-member-discardEmpty",
    "src/tokenizers/regexp-tokenizer.js~RegexpTokenizer#discardEmpty",
    "member"
  ],
  [
    "src/tokenizers/regexp-tokenizer.js~regexptokenizer#tokenize",
    "class/src/tokenizers/regexp-tokenizer.js~RegexpTokenizer.html#instance-method-tokenize",
    "src/tokenizers/regexp-tokenizer.js~RegexpTokenizer#tokenize",
    "method"
  ],
  [
    "src/tokenizers/sentence-tokenizer.js",
    "file/src/tokenizers/sentence-tokenizer.js.html",
    "src/tokenizers/sentence-tokenizer.js",
    "file"
  ],
  [
    "src/tokenizers/sentence-tokenizer.js~sentencetokenizer#tokenize",
    "class/src/tokenizers/sentence-tokenizer.js~SentenceTokenizer.html#instance-method-tokenize",
    "src/tokenizers/sentence-tokenizer.js~SentenceTokenizer#tokenize",
    "method"
  ],
  [
    "src/tokenizers/tokenizer.js",
    "file/src/tokenizers/tokenizer.js.html",
    "src/tokenizers/tokenizer.js",
    "file"
  ],
  [
    "src/tokenizers/tokenizer.js~tokenizer#attach",
    "class/src/tokenizers/tokenizer.js~Tokenizer.html#instance-method-attach",
    "src/tokenizers/tokenizer.js~Tokenizer#attach",
    "method"
  ],
  [
    "src/tokenizers/tokenizer.js~tokenizer#tokenize",
    "class/src/tokenizers/tokenizer.js~Tokenizer.html#instance-method-tokenize",
    "src/tokenizers/tokenizer.js~Tokenizer#tokenize",
    "method"
  ],
  [
    "src/tokenizers/tokenizer.js~tokenizer#trim",
    "class/src/tokenizers/tokenizer.js~Tokenizer.html#instance-method-trim",
    "src/tokenizers/tokenizer.js~Tokenizer#trim",
    "method"
  ],
  [
    "src/tokenizers/treebank-word-tokenizer.js",
    "file/src/tokenizers/treebank-word-tokenizer.js.html",
    "src/tokenizers/treebank-word-tokenizer.js",
    "file"
  ],
  [
    "src/tokenizers/treebank-word-tokenizer.js~treebankwordtokenizer#tokenize",
    "class/src/tokenizers/treebank-word-tokenizer.js~TreebankWordTokenizer.html#instance-method-tokenize",
    "src/tokenizers/treebank-word-tokenizer.js~TreebankWordTokenizer#tokenize",
    "method"
  ],
  [
    "src/util/bag.js",
    "file/src/util/bag.js.html",
    "src/util/bag.js",
    "file"
  ],
  [
    "src/util/bag.js~bag#add",
    "class/src/util/bag.js~Bag.html#instance-method-add",
    "src/util/bag.js~Bag#add",
    "method"
  ],
  [
    "src/util/bag.js~bag#constructor",
    "class/src/util/bag.js~Bag.html#instance-constructor-constructor",
    "src/util/bag.js~Bag#constructor",
    "method"
  ],
  [
    "src/util/bag.js~bag#contains",
    "class/src/util/bag.js~Bag.html#instance-method-contains",
    "src/util/bag.js~Bag#contains",
    "method"
  ],
  [
    "src/util/bag.js~bag#dictionary",
    "class/src/util/bag.js~Bag.html#instance-member-dictionary",
    "src/util/bag.js~Bag#dictionary",
    "member"
  ],
  [
    "src/util/bag.js~bag#isempty",
    "class/src/util/bag.js~Bag.html#instance-method-isEmpty",
    "src/util/bag.js~Bag#isEmpty",
    "method"
  ],
  [
    "src/util/bag.js~bag#nelement",
    "class/src/util/bag.js~Bag.html#instance-member-nElement",
    "src/util/bag.js~Bag#nElement",
    "member"
  ],
  [
    "src/util/bag.js~bag#unpack",
    "class/src/util/bag.js~Bag.html#instance-method-unpack",
    "src/util/bag.js~Bag#unpack",
    "method"
  ],
  [
    "src/util/stopwords.js",
    "file/src/util/stopwords.js.html",
    "src/util/stopwords.js",
    "file"
  ],
  [
    "src/util/topological.js",
    "file/src/util/topological.js.html",
    "src/util/topological.js",
    "file"
  ],
  [
    "src/util/topological.js~topological#constructor",
    "class/src/util/topological.js~Topological.html#instance-constructor-constructor",
    "src/util/topological.js~Topological#constructor",
    "method"
  ],
  [
    "src/util/topological.js~topological#isdag",
    "class/src/util/topological.js~Topological.html#instance-method-isDAG",
    "src/util/topological.js~Topological#isDAG",
    "method"
  ],
  [
    "src/util/topological.js~topological#isdag",
    "class/src/util/topological.js~Topological.html#instance-member-isDag",
    "src/util/topological.js~Topological#isDag",
    "member"
  ],
  [
    "src/util/topological.js~topological#order",
    "class/src/util/topological.js~Topological.html#instance-method-order",
    "src/util/topological.js~Topological#order",
    "method"
  ],
  [
    "src/util/topological.js~topological#sorted",
    "class/src/util/topological.js~Topological.html#instance-member-sorted",
    "src/util/topological.js~Topological#sorted",
    "member"
  ],
  [
    "src/util/utils.js",
    "file/src/util/utils.js.html",
    "src/util/utils.js",
    "file"
  ]
]